# Generated by Django 4.0.3 on 2022-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/placeholder.jpg', null=True, upload_to=''),
        ),
    ]
